server:
  port: 7001
  # location on classpath (e.g. src/main/resources/WEB in maven)
  static.classpath:
    location: "/WEB"
    context: "/web"

webservices:
  monkey-ws:
    description: "A ws that is in charge of evaluating monkey programs"
    uri: "http://localhost:8080"
    endpoints:
      evaluate: "/evaluate"

cache:
  description: "Access to Redis cache"
  host: "localhost"
  port: 6379

# DB connection
javax:
  sql:
    DataSource:
      blogDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          #  https://github.com/brettwooldridge/HikariCP
          url: jdbc:postgresql://localhost:5432/blogdb
          user: user
          password: password