kind: Service
apiVersion: v1
metadata:
  name: monkey-ws
  labels:
    app: monkey-ws
spec:
  type: NodePort
  selector:
    app: monkey-ws
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: monkey-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monkey-ws
  template:
    metadata:
      labels:
        app: monkey-ws
        version: v1
    spec:
      containers:
      - name: monkey-ws
        image: monkey-ws
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
