# TODO: Ideally this docker-compose should contain also redis and other services

version: '3.7'

services:
  blogdb:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - ./data:/var/lib/postgresql
    command: ["postgres", "-c", "log_statement=all"]