name: CI for monkey monorepo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # setup JDK 11, build and test monkey interpreter
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build monkey interpreter
      run:  mvn clean install --file pom.xml -DskipTests
    - name: Test monkey interpreter
      run: mvn test --file pom.xml

      # setup JDK 21, build and test webservices
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build monkey-ws
      run: cd ./microservices/monkey-ws/ &&  mvn clean install --file pom.xml -DskipTests
    - name: Test monkey-ws
      run: cd ./microservices/monkey-ws/ && mvn test --file pom.xml
    - name: Build playground-ws
      run: cd ./microservices/playground-ws/ &&  mvn clean install --file pom.xml -Pdev -DskipTests
    - name: Test playground-ws
      run: cd ./microservices/playground-ws/ && mvn test --file pom.xml

      # setup node 18, test playground
    - name: Setup node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install playground dependencies
      run: cd ./web/playground && npm i
    - name: Build playground
      run: cd ./web/playground && npm run build
    - name: Run playground tests
      run: cd ./web/playground && npm run test